### ISSUE TITLE
Twitterscraper was working fine till tuesday but now it shows 0 tweets 

### ISSUE THREAD

**Issue by lubhaniagarwal** [taspinar/twitterscraper#299] opened 2020-06-04 10:01 UTC
I am facing problem while retrieving tweets with twitterscraper as it was working fine till tuesday but now it shows 0 tweets. 
I even tried to clone the git repository and change header list, but still it is not working.
Is there anyway to fix this issue or anything wrong on twitterscraper side.
please help me out !!:((

**Comment by hakanyusufoglu** [comment] 2020-06-04 10:03
Yes me too. Problem is back. Please help !

**Comment by lapp0** [comment] 2020-06-04 19:19
Please share the command you're running, and any input files so I can try to reproduce.

**Comment by lubhaniagarwal** [comment] 2020-06-04 19:27
first installed twitterscraper using pip install twitterscraper. It was working fine till tuesday.
then i uninstalled it 
cloned repo-https://github.com/taspinar/twitterscraper.git
changed the header list in query.py to :HEADERS_LIST = ['Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36']
then run - python setup.py install 

but its not working.

command that i am working on is:

twitterscraper "amazon locker" -bd 2010-01-01 -ed 2020-05-26 --limit 100000 --lang en --output xyz.json

thanks a lot.

**Comment by lapp0** [comment] 2020-06-04 19:50
I ran it from origin/master without making any changes to the headers and got 653 results. Could you share the programs full output?

**Comment by lubhaniagarwal** [comment] 2020-06-04 20:00
[error.txt](https://github.com/taspinar/twitterscraper/files/4732428/error.txt)
here  is the commands I'm running on command prompt and results that i get .
thank you

**Comment by lapp0** [comment] 2020-06-04 20:26
I'm not sure why I was able to retrieve tweets. It appears other users are suggesting twitter doesn't allow JS disabled.

https://github.com/taspinar/twitterscraper/issues/296#issuecomment-638791009

I will try to hack together a selenium solution tonight.

**Comment by lubhaniagarwal** [comment] 2020-06-04 20:28
Okayy.
Thank you so much for your inputs.

**Comment by lapp0** [comment] 2020-06-05 03:51
Please try this and let me know how it works for you https://github.com/taspinar/twitterscraper/pull/302

**Comment by abhisheksaxena1998** [comment] 2020-06-05 04:47
HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}

This line in query.py will surely fix this issue.

**Comment by lubhaniagarwal** [comment] 2020-06-05 06:22
@abhisheksaxena1998  thanks a lot .It started working now.
@lapp0 I will try this #302  and let you know. Thanks you so much! :)

**Comment by lapp0** [comment] 2020-06-05 17:25
Duplicate of https://github.com/taspinar/twitterscraper/issues/296

**Comment by lapp0** [comment] 2020-06-05 17:26
@lubhaniagarwal other users are suggesting that legacy now works, give `origin/master` another try

**Closed by lapp0** 2020-06-05 17:25 UTC
