### ISSUE TITLE
Tweet object has no attribute "encode"

### ISSUE THREAD

**Issue by arsalanamjid** [taspinar/twitterscraper#86] opened 2018-02-01 17:03 UTC
![image](https://user-images.githubusercontent.com/12942379/35691944-b3bdf250-079b-11e8-85f7-50939e924d18.png)

**Comment by taspinar** [comment] 2018-02-02 12:37
I believe this is an duplicate of https://github.com/taspinar/twitterscraper/issues/56

**Closed by taspinar** 2018-02-02 12:37 UTC
