### ISSUE TITLE
Scraper still working ?

### ISSUE THREAD

**Issue by AlexBietrix** [taspinar/twitterscraper#298] opened 2020-06-02 22:07 UTC
I am using the scraper since a few weeks for a project. The program was working fine, however since yesterday I am not able to retrieve data from Twitter anymore...

For instance when I am using the example : twitterscraper Trump --limit 1000 --output=tweets.json I got 0 tweets.

Same when using query_user_info, I got now NoneType object. 

Did Twitter fix something about scraping with BeautifulSoup ? 

Thanks for your answer and help. 

Best regards, 
Alex Bietrix

**Comment by mardiaz353** [comment] 2020-06-02 23:36
I ran into the same issue.

**Comment by BetoJam** [comment] 2020-06-03 00:44
Maybe is the same issue reported and solved here:

https://github.com/taspinar/twitterscraper/issues/296

**Comment by AlexBietrix** [comment] 2020-06-03 00:47
> Maybe is the same issue reported and solved here:
> 
> #296

Yes thank you ! It works now to retrieve the tweets. However I get this error when I want to have user info : local variable 'user_info' referenced before assignment

**Comment by christ182** [comment] 2020-06-04 02:33
> Maybe is the same issue reported and solved here:
> 
> #296

I tried this solution today. It does not seem to work anymore

**Comment by barabelha** [comment] 2020-06-04 02:45
#296 does not work anymore. I tried today and keep receiving the same thing "0 tweets"

**Comment by romit-actuarial** [comment] 2020-06-04 10:24
Yea, #296  stopped working. Would be great if someone can help! 

Thanks!

**Comment by lapp0** [comment] 2020-06-05 03:51
Please try this and let me know how it works for you https://github.com/taspinar/twitterscraper/pull/302

**Comment by lapp0** [comment] 2020-06-05 17:25
Duplicate of https://github.com/taspinar/twitterscraper/issues/296

**Closed by lapp0** 2020-06-05 17:25 UTC

**Comment by zhicheng0501** [comment] 2020-06-15 13:02
> > Maybe is the same issue reported and solved here:
> > #296
> 
> Yes thank you ! It works now to retrieve the tweets. However I get this error when I want to have user info, using query_user_info : local variable 'user_info' referenced before assignment

have you solved the problem?
