### ISSUE TITLE
Stop before downloading all tweets

### ISSUE THREAD

**Issue by stagenam3** [taspinar/twitterscraper#288] opened 2020-05-04 18:38 UTC
No matter how short the time period I put, I always get "has_more_tweets". 
Username stops at 688 tweets
Scrapes on words stop at around 12 500 tweets. 
Any workaround would be appreciated. Thanks!

**Comment by lapp0** [comment] 2020-06-07 21:28
Twitter has a limitation on number of tweets you can retrieve from a user profile. There is a workaround with the `-j` option in this PR https://github.com/taspinar/twitterscraper/commit/8786a5789f8686d4022f14ff44b7ffd86a5abd11

Closing because this is a duplicate of https://github.com/taspinar/twitterscraper/issues/305

**Closed by lapp0** 2020-06-07 21:28 UTC
