### ISSUE TITLE
Error module

### ISSUE THREAD

**Issue by barripdmx** [taspinar/twitterscraper#127] opened 2018-06-29 10:36 UTC
I get this:
> python.exe: can't find '__main__' module in 'twitterscraper'

any solution?

Gracias,
jb

**Comment by barripdmx** [comment] 2018-07-01 11:17
1- clone in root directory
2 - python setup.py install

> PS C:\twitterscraper-master> python setup.py install
> running install
> running bdist_egg
> running egg_info
> creating twitterscraper.egg-info
> writing requirements to twitterscraper.egg-info\requires.txt
> writing twitterscraper.egg-info\PKG-INFO
> writing top-level names to twitterscraper.egg-info\top_level.txt
> writing dependency_links to twitterscraper.egg-info\dependency_links.txt
> writing entry points to twitterscraper.egg-info\entry_points.txt
> writing manifest file 'twitterscraper.egg-info\SOURCES.txt'
> reading manifest file 'twitterscraper.egg-info\SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no files found matching 'LICENSE.txt'
> warning: no files found matching 'HISTORY.rst'
> writing manifest file 'twitterscraper.egg-info\SOURCES.txt'
> installing library code to build\bdist.win32\egg
> running install_lib
> running build_py
> creating build
> creating build\lib
> creating build\lib\twitterscraper
> copying twitterscraper\logging.py -> build\lib\twitterscraper
> copying twitterscraper\main.py -> build\lib\twitterscraper
> copying twitterscraper\query.py -> build\lib\twitterscraper
> copying twitterscraper\tweet.py -> build\lib\twitterscraper
> copying twitterscraper\__init__.py -> build\lib\twitterscraper
> creating build\bdist.win32
> creating build\bdist.win32\egg
> creating build\bdist.win32\egg\twitterscraper
> copying build\lib\twitterscraper\logging.py -> build\bdist.win32\egg\twitterscraper
> copying build\lib\twitterscraper\main.py -> build\bdist.win32\egg\twitterscraper
> copying build\lib\twitterscraper\query.py -> build\bdist.win32\egg\twitterscraper
> copying build\lib\twitterscraper\tweet.py -> build\bdist.win32\egg\twitterscraper
> copying build\lib\twitterscraper\__init__.py -> build\bdist.win32\egg\twitterscraper
> byte-compiling build\bdist.win32\egg\twitterscraper\logging.py to logging.pyc
> byte-compiling build\bdist.win32\egg\twitterscraper\main.py to main.pyc
> byte-compiling build\bdist.win32\egg\twitterscraper\query.py to query.pyc
> byte-compiling build\bdist.win32\egg\twitterscraper\tweet.py to tweet.pyc
> byte-compiling build\bdist.win32\egg\twitterscraper\__init__.py to __init__.pyc
> creating build\bdist.win32\egg\EGG-INFO
> copying twitterscraper.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
> copying twitterscraper.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
> copying twitterscraper.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
> copying twitterscraper.egg-info\entry_points.txt -> build\bdist.win32\egg\EGG-INFO
> copying twitterscraper.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
> copying twitterscraper.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
> zip_safe flag not set; analyzing archive contents...
> creating dist
> creating 'dist\twitterscraper-0.7.1-py2.7.egg' and adding 'build\bdist.win32\egg' to it
> removing 'build\bdist.win32\egg' (and everything under it)
> Processing twitterscraper-0.7.1-py2.7.egg
> Copying twitterscraper-0.7.1-py2.7.egg to c:\python27\lib\site-packages
> Adding twitterscraper 0.7.1 to easy-install.pth file
> Installing twitterscraper-script.py script to C:\Python27\Scripts
> Installing twitterscraper.exe script to C:\Python27\Scripts
> Installing twitterscraper.exe.manifest script to C:\Python27\Scripts
> 
> Installed c:\python27\lib\site-packages\twitterscraper-0.7.1-py2.7.egg
> Processing dependencies for twitterscraper==0.7.1
> Searching for requests
> Reading https://pypi.python.org/simple/requests/
> Downloading https://files.pythonhosted.org/packages/54/1f/782a5734931ddf2e1494e4cd615a51ff98e1879cbe9eecbdfeaf09aa75e9/requests-2.19.1.tar.gz#sha256=ec22d826a36ed72a7358ff3fe56cbd4ba69dd7a6718ffd450ff0e9df7a47ce6a
> Best match: requests 2.19.1
> Processing requests-2.19.1.tar.gz
> Writing c:\users\jbarr\appdata\local\temp\easy_install-ytp7jx\requests-2.19.1\setup.cfg
> Running requests-2.19.1\setup.py -q bdist_egg --dist-dir c:\users\jbarr\appdata\local\temp\easy_install-ytp7jx\requests-2.19.1\egg-dist-tmp-bxszbe
> C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
>   warnings.warn(msg)
> warning: no files found matching 'NOTICE'
> warning: no files found matching 'requirements.txt'
> creating c:\python27\lib\site-packages\requests-2.19.1-py2.7.egg
> Extracting requests-2.19.1-py2.7.egg to c:\python27\lib\site-packages
> Adding requests 2.19.1 to easy-install.pth file
> 
> Installed c:\python27\lib\site-packages\requests-2.19.1-py2.7.egg
> Searching for lxml
> Reading https://pypi.python.org/simple/lxml/
> Downloading https://files.pythonhosted.org/packages/54/a6/43be8cf1cc23e3fa208cab04ba2f9c3b7af0233aab32af6b5089122b44cd/lxml-4.2.3.tar.gz#sha256=622f7e40faef13d232fb52003661f2764ce6cdef3edb0a59af7c1559e4cc36d1
> Best match: lxml 4.2.3
> Processing lxml-4.2.3.tar.gz
> Writing c:\users\jbarr\appdata\local\temp\easy_install-eysfmx\lxml-4.2.3\setup.cfg
> Running lxml-4.2.3\setup.py -q bdist_egg --dist-dir c:\users\jbarr\appdata\local\temp\easy_install-eysfmx\lxml-4.2.3\egg-dist-tmp-orrkys
> Building lxml version 4.2.3.
> Building without Cython.
> ERROR: "xslt-config" no se reconoce como un comando interno o externo,
> programa o archivo por lotes ejecutable.
> 
> ** make sure the development packages of libxml2 and libxslt are installed **
> 
> Using build configuration of libxslt
> error: Setup script exited with error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27

3- PS C:\twitterscraper-master> python twitterscraper Trump --limit 100 --output=tweets.json

> C:\Python27\python.exe: can't find '__main__' module in 'twitterscraper'

**Comment by lapp0** [comment] 2018-07-03 23:20
Sorry, not familiar with pythons behavior on windows. On gnu/linux is run `twitterscraper Trump --limit 100 --output=tweets.json` (without the `python` at the beginning). 

Can you try running it without the `python` at the beginning?

**Comment by lapp0** [comment] 2018-07-06 01:32
I can confirm that this is an issue on my end as well. I am getting non-deterministic failures. Looking into it.

**Comment by taspinar** [comment] 2018-07-07 14:13
It looks like you have python 2.7 installed on a windows machine. I strongly suggest you to install Python version 3, since 2.7 will no longer be maintained past 2020. See [here](https://pythonclock.org/)

Try to install it with [Anaconda Navigator](https://www.anaconda.com/download/#windows). Anaconda is a Python package manager and besides Python it contains among others the most popular packages, so not having the libxml module should not be a problem.

**Comment by barripdmx** [comment] 2018-07-09 18:41
Instalation OK?

root@taller-datos-twitter:/home/taller# 
root@taller-datos-twitter:/home/taller# sudo pip install twitterscraper
Requirement already satisfied: twitterscraper in /usr/local/lib/python2.7/dist-packages (0.7.1)
Requirement already satisfied: bs4 in /usr/local/lib/python2.7/dist-packages (from twitterscraper) (0.0.1)
Requirement already satisfied: lxml in /usr/lib/python2.7/dist-packages (from twitterscraper) (3.5.0)
Requirement already satisfied: coala-utils~=0.5.0 in /usr/local/lib/python2.7/dist-packages (from twitterscraper) (0.5.1)
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from twitterscraper) (2.9.1)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages (from bs4->twitterscraper) (4.4.1)
root@taller-datos-twitter:/home/taller#

**Comment by taspinar** [comment] 2018-07-09 19:35
Yes that looks good.

**Comment by barripdmx** [comment] 2018-07-09 21:39
ok.

I do the test but it does not work

> root@taller-datos-twitter:/home/taller# 
> root@taller-datos-twitter:/home/taller# twitterscraper Trump --limit 100 --output=tweets.json
> Traceback (most recent call last):
>   File "/usr/local/bin/twitterscraper", line 7, in <module>
>     from twitterscraper.main import main
>   File "/usr/local/lib/python2.7/dist-packages/twitterscraper/__init__.py", line 13, in <module>
>     from twitterscraper.query import query_tweets
>   File "/usr/local/lib/python2.7/dist-packages/twitterscraper/query.py", line 10, in <module>
>     from twitterscraper.logging import logger
>   File "/usr/local/lib/python2.7/dist-packages/twitterscraper/logging.py", line 4, in <module>
>     logger = logging.getLogger('twitterscraper')
> AttributeError: 'module' object has no attribute 'getLogger'
> root@taller-datos-twitter:/home/taller# 


any solution?

**Comment by lapp0** [comment] 2018-07-17 01:11
hello can you please try the branch in this pull request? Should fix it https://github.com/taspinar/twitterscraper/pull/135

**Comment by taspinar** [comment] 2018-07-18 17:15
PR #135 has been merge and version 0.8.0 has been uploaded to PyPi. This issue should be fixed.

**Closed by taspinar** 2018-07-18 17:15 UTC
